### GET all categories
GET http://localhost:8080/api/category/all

### GET category by ID
GET http://localhost:8080/api/category/1

### Create new category
POST http://localhost:8080/api/category/create
Content-Type: application/json

{
  "categoryName": "Console",
  "categoryDescription": "Consoles are dedicated gaming devices that are designed to play video games."
}

### Update an existing category
PUT http://localhost:8080/api/category/update/6
Content-Type: application/json

{
  "categoryName": "JRPG",
  "categoryDescription": "JRPGs are games that emphasize story-telling, character development, and exploration."
}

### Delete a category
DELETE http://localhost:8080/api/category/delete/2